/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBlindRouteImport } from './routes/_app/blind'
import { Route as AppDonorsRouteImport } from './routes/_app/donors'
import { Route as AppResultsRouteImport } from './routes/_app/results'
import { Route as AppTrendsRouteImport } from './routes/_app/trends'
import { Route as AppVoicesRouteImport } from './routes/_app/voices'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBlindRoute = AppBlindRouteImport.update({
  id: '/blind',
  path: '/blind',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorsRoute = AppDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppVoicesRoute = AppVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/blind': typeof AppBlindRoute
  '/donors': typeof AppDonorsRoute
  '/results': typeof AppResultsRoute
  '/trends': typeof AppTrendsRoute
  '/voices': typeof AppVoicesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/blind': typeof AppBlindRoute
  '/donors': typeof AppDonorsRoute
  '/results': typeof AppResultsRoute
  '/trends': typeof AppTrendsRoute
  '/voices': typeof AppVoicesRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/blind': typeof AppBlindRoute
  '/_app/donors': typeof AppDonorsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/trends': typeof AppTrendsRoute
  '/_app/voices': typeof AppVoicesRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/blind'
    | '/donors'
    | '/results'
    | '/trends'
    | '/voices'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/blind'
    | '/donors'
    | '/results'
    | '/trends'
    | '/voices'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/blind'
    | '/_app/donors'
    | '/_app/results'
    | '/_app/trends'
    | '/_app/voices'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blind': {
      id: '/_app/blind'
      path: '/blind'
      fullPath: '/blind'
      preLoaderRoute: typeof AppBlindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donors': {
      id: '/_app/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof AppDonorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voices': {
      id: '/_app/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof AppVoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBlindRoute: typeof AppBlindRoute
  AppDonorsRoute: typeof AppDonorsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppVoicesRoute: typeof AppVoicesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBlindRoute: AppBlindRoute,
  AppDonorsRoute: AppDonorsRoute,
  AppResultsRoute: AppResultsRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppVoicesRoute: AppVoicesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
